import random
from datetime import datetime
from PreguntasApp import preguntas as pre
from django.shortcuts import render

from PreguntasApp.models import Pregunta


# Create your views here.
def inicio(request):
    return render(request, 'inicio.html')

def preguntas(request):
    empezar = False
    pregunta = ""
    if request.method == 'POST':
        empezar = True
        if request.POST.get('empezar'):
            pre.empezar()
        elif request.POST.get('pregunta'):
            pregunta = pre.extraer_pregunta()
        elif request.POST.get('terminar'):
            empezar = False
            pre.reiniciar()



    return render(request, 'preguntas.html', {'empezar': empezar, 'pregunta': pregunta, 'preguntas_respondidas':pre.preguntas_respondiodias})



# preguntas = [
    #     "¿Cuáles son tus Red Flags a la hora de salir amorosamente con alguien?",
    #     "Menciona algo que las personas de tu sexo opuesto sepan hacer muy bien.",
    #     "Menciona algo que las personas de tu sexo opuesto no sepan hacer nada bien.",
    #     "¿Cuánto tiempo sueles pasar solo?",
    #     "¿Pierdes interés cuando un chico/a te ama demasiado?",
    #     "¿Qué indirectas le haces al / a la que te gusta?",
    #     "¿Dónde has metido la polla en este último mes?",
    #     "¿Qué es lo que menos te gusta de ti cuando te enamoras?",
    #     "¿Quién va primero el/la novio/a o los mejores amigos?",
    #     "Di una frase de tu película favorita.",
    #     "¿Por qué podrías ir a la cárcel?",
    #     "¿Por qué podrías ir a la cárcel? Que respondan tus amigos.",
    #     "¿Cuál es la canción que te hace sentir en paz?",
    #     "¿Quieres dejar de ocultar algo?",
    #     "¿Cuál es el video más largo que te has visto?",
    #     "¿Cuál es la peli que más te recuerda a tus padres?",
    #     "¿Qué cultura te gusta más la oriental o la occidental?",
    #     "Tienes cascos alámbricos o inalámbricos.",
    #     "¿Cuál es tu prenda favorita?",
    #     "¿Cuánto tiempo puede estar el agua de tu cuarto encima de tu mesa?",
    #     "¿Qué cosas te estás perdiendo de la vida?",
    #     "Di 3 cosas por las que merece la pena vivir.",
    #     "¿Cuál es el jefe de videojuego que más te ha costado matar?",
    #     "¿Cómo es tu cartera?",
    #     "¿Cuál es el mejor juego para jugar en clase?",
    #     "¿De qué tendría que haber una aplicación?",
    #     "¿Qué preguntarías al rey?",
    #     "¿Cuál es el mejor rey?",
    #     "¿Cuál es el mejor rey de tu país?",
    #     "Di 5 razones por las que se debería o no tener novio/a.",
    #     "¿Te gusta la poesía?",
    #     "¿Cuál es tu canción de amor?",
    #     "¿Alguna vez alguien te ha dedicado una playlist?",
    #     "¿Qué canción no puedes poner en ningún lado, pero te encanta?",
    #     "¿Qué es una persona sin emociones?",
    #     "¿Quién es superior a ti?",
    #     "Estas en una boda, arruínala en 3 palabras.",
    #     "¿A qué lugar irías si fueras invisible?",
    #     "¿Qué es lo más intocable de tu teléfono?",
    #     "¿Qué es lo malo del odio?",
    #     "Cuando estas durmiendo en casa de tu amigo ¿De qué eres? De despertarte antes que tu amigo, de levantarte a la vez o de despertar después.",
    #     "¿Cuál es el meme que siempre te hace reír?",
    #     "¿Dejas que tu mente tome el control de tus sentimientos?",
    #     "¿Qué es lo más bizarro que se te ha pasado por la cabeza?",
    #     "¿Qué cosa estás postergando que es importante para ti? ¿Por qué lo haces?",
    #     "Si estuvieras en un lugar con todas las cosas que has perdido ¿Qué sería lo primero que buscarías?",
    #     "Si estuvieras en un lugar con todos los amigos que has perdido ¿A quién buscarías primero?",
    #     "¿Qué pasaría si con solo pensar un deseo se cumple?",
    #     "¿Sabes que hay personas que de verdad se preocupan por ti?",
    #     "¿Cuál es tu dejar en visto más largo?",
    #     "¿Cuál es tu terapia cuando estas mal?",
    #     "¿Con quién eres más competitivo?",
    #     "¿Tuviste buena infancia?",
    #     "Di 5 canciones que te cambiaron la vida",
    #     "¿Qué canción no puedes escuchar?",
    #     "¿Qué canciones enseñarías a tus nietos?",
    #     "¿A quién te pillarías?",
    #     "¿Qué canción enseñarías a tus hijos?",
    #     "¿Cuánto te mide la polla?",
    #     "¿Cuál es tu álbum musical favorito?",
    #     "¿Cuál es el estado de ánimo más desagradable?",
    #     "¿Te gustan las pegatinas?",
    #     "¿Cuáles son tus bienaventuranzas?",
    #     "¿Qué opinas de la frase Todos/as son iguales?",
    #     "Si pudieras ser un personaje de dibujos animados. ¿Quién serías y por qué?",
    #     "¿Cómo te gustaría decorar tu cuarto?",
    #     "¿Tienes pito?",
    #     "¿Cuál es tu opinión sobre legalizar la prostitución?",
    #     "¿Qué es lo que más valoras de la amistad?",
    #     "¿Un piquito?",
    #     "¿Los números pares y naturales son más que los números naturales?",
    #     "¿Qué es lo más absurdo que guardas? ¿Por qué?",
    #     "Unicoos o Susiprofe",
    #     "¿Qué necesitas para estar feliz?",
    #     "¿Cómo crees que la globalización ha afectado a la cultura?",
    #     "¿Cuál es la cosa más rara que te ha pasado?",
    #     "¿Qué opinas de la libertad de expresión?",
    #     "¿Quién ganaría en un torneo de piedra, papel o tijeras?",
    #     "¿Te gusta la ópera?",
    #     "¿A qué comunidad muerta perteneces?",
    #     "¿Qué juego es nada sin mods?",
    #     "¿Cuál ha sido el mejor momento de tu vida?",
    #     "¿Verías ético clonar dinosaurios?",
    #     "Di una serie para hacer un maratón",
    #     "Di una canción que te haga llorar",
    #     "¿Te drogas?",
    #     "Educación tradicional o educación en línea",
    #     "¿Crees que está aumentando el sexo entre menores?",
    #     "Califica del 1 al 10 a la persona de tu derecha",
    #     "¿Cuál es la despedida más triste que has tenido?",
    #     "¿Cómo te han ido las notas?",
    #     "¿Si ser delito fuera un disléxico? ¿Lo serías?",
    #     "¿Estás hot?",
    #     "¿Dónde te gusta guardar tus cosas?",
    #     "¿Qué piensas que es lo más importante de una relación de amistad?",
    #     "¿Cuál es tu perspectiva sobre la inteligencia artificial en la toma de decisiones éticas?",
    #     "¿Qué es lo más absurdo que has hecho?",
    #     "¿Cuál es el peor hábito que tienes?",
    #     "¿Te la han chupado alguna vez?",
    #     "Piscina o playa",
    #     "¿Te gustaría que una inteligencia extraterrestre suficientemente avanzada como para contactar con nosotros contacte con nosotros?",
    #     "¿Cómo te gustaría bailar con un/a chico/a?",
    #     "¿Cuál es el videojuego que más te ha marcado?",
    #     "¿A quién le tienes que dar las gracias por algo? Si está presente te invito a que se las des.",
    #     "¿Cómo te va la vida?",
    #     "¿Te gusta dibujar?",
    #     "¿Qué es la cosa más antigua que conservas?",
    #     "¿Cuál es la mejor comida? El desayuno, media mañana, la comida, la merienda, la cena o comerse el frigorífico a las 3am.",
    #     "¿Tu historial de youtube está limpio o sucio?",
    #     "¿Cuál es tu opinión sobre el feminismo?",
    #     "¿Qué opinas de que yo solo sé que no sé nada?",
    #     "¿Crees que las redes sociales están mal reguladas?",
    #     "¿Cuál ha sido el mejor día con los panas?",
    #     "¿Cuál es peor el baño de los hombres o el de las mujeres?",
    #     "¿Qué deporte te gustaría que existiese?",
    #     "¿A quién le darías tu muñeco vudú?",
    #     "¿Te identificas con alguna canción?",
    #     "¿Qué opinas de las personas que hablan demasiado de lo que saben?",
    #     "¿Qué juego juegas últimamente?",
    #     "¿Si pudieras ser famoso por algo, de que te gustaría destacar?",
    #     "Haz una tierlist de las comunidades autónomas",
    #     "¿Cuál ha sido la película con la mayor traición?",
    #     "¿Crees en los extraterrestres?",
    #     "¿Por qué os gustan los dildos?",
    #     "¿Cuál es tu coche favorito?",
    #     "¿Me tienes que contar alguna cosa importante que no sepa o que esté en duda?",
    #     "Di una canción para declararte al amor de tu vida.",
    #     "¿Cuántas cosas llevas en la cartera?",
    #     "El conjunto formado por todos los conjuntos que no son miembros de sí mismos. ¿Es acaso miembro de sí mismo?",
    #     "¿Cuál ha sido la serie más cursi que has visto?",
    #     "¿Crees que debería de haber restricciones en el acceso a las redes sociales?",
    #     "¿Cuál es la serie más dramática que has visto?",
    #     "¿Qué es lo que más orgullo te da?",
    #     "¿Cuál ha sido la gestión más problemática que has hecho?",
    #     "¿Qué amigo hace tiempo que no ves?",
    #     "¿Cuál es el juego con más perros jugando?",
    #     "¿A qué hora te sueles acostar?",
    #     "¿Te gusta pescar en los videojuegos?",
    #     "¿Qué es un amigo?",
    #     "¿Cómo crees que la religión afecta a nuestras vidas?",
    #     "Di 5 canciones para el fin del mundo",
    #     "¿Qué pasaría si se desvelasen las ideas políticas de tu grupo de amigos?",
    #     "¿Qué es lo más interesante que te has apostado a piedra papel o tijeras?",
    #     "¿Cuánto pesas?",
    #     "¿Piensas con frecuencia cómo te sientes?",
    #     "¿Crees que las redes sociales solapan la información?",
    #     "Prefieres enviar mensajes de texto o audios",
    #     "Si te pudieras cambiar el nombre ¿Cuál elegirías?",
    #     "¿Cuál es la cosa más cara que has comprado sin necesidad?",
    #     "¿La tortilla tiene o no tiene que tener cebolla?",
    #     "¿Qué amigo es más raro?",
    #     "¿Qué es lo que más miedo te da?",
    #     "Si tu vida fuese una película, ¿Cómo se llamaría?",
    #     "¿Qué opinas de las relaciones abiertas?",
    #     "¿Quién fue el último en el que pensaste en acostarte?",
    #     "¿Cuáles son las ventajas y desventajas del capitalismo?",
    #     "Si pudieras vivir en cualquier país del mundo, ¿dónde vivirías y por qué?",
    #     "¿Cuál es el lugar más raro donde has tenido sexo?",
    #     "¿Cuál ha sido tu mayor fracaso?",
    #     "¿Tienes algo que quisieras contar pero no te atreves?",
    #     "¿Qué superpoder te gustaría tener?",
    #     "¿Cuál es tu mayor sueño?",
    #     "¿Qué opinas sobre las aplicaciones de citas?",
    #     "¿Has tenido algún encuentro paranormal?",
    #     "¿Cuál es tu serie animada favorita?",
    #     "Si pudieras borrar un recuerdo, ¿cuál sería?",
    #     "¿Qué cosa valoras más en una relación amorosa?",
    #     "¿Cuál es el peor libro que has leído?",
    #     "¿Qué opinas sobre la eutanasia?",
    #     "¿Cuál es tu cita favorita?",
    #     "¿Cuál es tu actividad favorita para relajarte?",
    #     "¿Cómo definirías la libertad?",
    #     "¿Crees que existe vida después de la muerte?",
    #     "¿Cuál es el destino de tus sueños para unas vacaciones?",
    #     "¿Cuál es la mejor época de tu vida?",
    #     "¿Cuál es el mayor reto que has superado?",
    #     "¿Prefieres el día o la noche?",
    #     "¿Qué opinas sobre la pena de muerte?",
    #     "¿Cuál es tu opinión sobre el cambio climático?",
    #     "¿Cuál es tu bebida alcohólica favorita?",
    #     "¿Qué es lo más loco que has hecho por amor?",
    #     "¿Qué personaje histórico admiras más?",
    #     "Si pudieras cenar con cualquier persona, viva o muerta, ¿quién sería?",
    #     "¿Cuál es tu peor miedo?",
    #     "¿Cuál es tu género musical favorito?",
    #     "¿Qué es lo que más te molesta de la sociedad actual?",
    #     "¿Crees que el dinero puede comprar la felicidad?",
    #     "¿Cuál es tu juego de mesa favorito?",
    #     "¿Qué es lo primero que piensas cuando te despiertas?",
    #     "¿Qué animal te gustaría ser y por qué?",
    #     "¿Qué país te gustaría visitar y por qué?",
    #     "¿Cuál es tu película de terror favorita?",
    #     "¿Crees que los sueños tienen significado?",
    #     "¿Cuál es tu deporte favorito para practicar?",
    #     "¿Qué opinas sobre la inteligencia artificial?",
    #     "¿Qué es lo que más extrañas de tu infancia?",
    #     "¿Qué cualidad valoras más en una persona?",
    #     "¿Cuál es tu peor hábito?",
    #     "¿Qué habilidad te gustaría aprender?",
    #     "¿Cuál es tu programa de televisión favorito?",
    #     "¿Prefieres leer libros o ver películas?",
    #     "¿Qué es lo que más te gusta de tu trabajo?",
    #     "¿Cuál es tu restaurante favorito?",
    #     "¿Cuál es tu cita favorita de una película?",
    #     "¿Qué prefieres, playa o montaña?",
    #     "¿Cuál es tu estación del año favorita?",
    #     "¿Qué te hace sentir más orgulloso de ti mismo?",
    #     "¿Qué opinas sobre el aborto?",
    #     "¿Qué prefieres, el amor o el dinero?",
    #     "¿Cuál es tu red social favorita?",
    #     "¿Qué es lo más importante para ti en la vida?",
    #     "¿Qué opinas sobre la guerra?",
    #     "¿Qué prefieres, vivir en la ciudad o en el campo?",
    #     "¿Qué es lo más importante para ti en una relación?",
    #     "¿Cuál es tu película favorita de todos los tiempos?",
    #     "¿Qué opinas sobre la política actual?",
    #     "¿Cuál es tu libro favorito?",
    #     "¿Qué harías si fueras presidente por un día?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor logro?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te gustaría cambiar de ti mismo?",
    #     "¿Qué opinas sobre el matrimonio?",
    #     "¿Cuál es tu festividad favorita?",
    #     "¿Qué prefieres, perros o gatos?",
    #     "¿Cuál es tu mayor talento?",
    #     "¿Qué prefieres, viajar en el tiempo al pasado o al futuro?",
    #     "¿Cuál es tu videojuego favorito?",
    #     "¿Qué harías si ganaras la lotería?",
    #     "¿Cuál es tu fruta favorita?",
    #     "¿Qué te hace más feliz?",
    #     "¿Cuál es tu hobby favorito?",
    #     "¿Qué prefieres, dulces o salados?",
    #     "¿Cuál es tu flor favorita?",
    #     "¿Qué opinas sobre la tecnología en la educación?",
    #     "¿Qué prefieres, ser rico y solitario o pobre y rodeado de amigos?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué opinas sobre las redes sociales?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu día de la semana favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu postre favorito?",
    #     "¿Qué opinas sobre el teletrabajo?",
    #     "¿Qué prefieres, leer un libro o escuchar un audiolibro?",
    #     "¿Cuál es tu actividad favorita en el tiempo libre?",
    #     "¿Qué opinas sobre el veganismo?",
    #     "¿Qué prefieres, una casa grande en el campo o un apartamento pequeño en la ciudad?",
    #     "¿Cuál es tu cita favorita?",
    #     "¿Qué prefieres, trabajar en algo que amas con un salario bajo o en algo que odias con un salario alto?",
    #     "¿Cuál es tu serie de televisión favorita?",
    #     "¿Qué prefieres, un verano caluroso o un invierno frío?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Qué opinas sobre el trabajo voluntario?",
    #     "¿Cuál es tu libro favorito?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu animal favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te gusta más, el café o el té?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, vivir en una casa en la playa o en una cabaña en la montaña?",
    #     "¿Qué opinas sobre la educación en línea?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, una película de comedia o una película de drama?",
    #     "¿Qué es lo más importante para ti en la vida?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué prefieres, un día lluvioso o un día soleado?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu deporte favorito para ver?",
    #     "¿Qué opinas sobre el cambio climático?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu mayor reto?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te gusta más, la playa o la montaña?",
    #     "¿Qué prefieres, un libro o una película?",
    #     "¿Qué es lo más importante para ti en una relación?",
    #     "¿Qué prefieres, vivir en la ciudad o en el campo?",
    #     "¿Cuál es tu mayor logro?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te gusta más, el café o el té?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu libro favorito?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te gusta más, el día o la noche?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu deporte favorito para practicar?",
    #     "¿Qué prefieres, un verano caluroso o un invierno frío?",
    #     "¿Qué te gusta más, la playa o la montaña?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu libro favorito?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué te gusta más, el café o el té?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu deporte favorito para practicar?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te gusta más, el día o la noche?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu libro favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te gusta más, el día o la noche?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te gusta más, el café o el té?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te gusta más, el amanecer o el atardecer?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué te gusta más, el día o la noche?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te gusta más, el día o la noche?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más vivo?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué te hace reír más?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Qué prefieres, el día o la noche?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, una vida larga y aburrida o una vida corta y emocionante?",
    #     "¿Cuál es tu color favorito?",
    #     "¿Cuál es tu mayor inspiración?",
    #     "¿Cuál es tu género de música favorito?",
    #     "¿Qué prefieres, una comida casera o una comida en un restaurante?",
    #     "¿Qué prefieres, el amanecer o el atardecer?",
    #     "¿Qué te hace reír más?",
    #     "¿Qué prefieres, una vida tranquila o una vida llena de aventuras?",
    #     "¿Qué prefieres, una casa en la playa o una cabaña en la montaña?",
    #     "¿Qué prefieres, el verano o el invierno?",
    #     "¿Qué te hace sentir más feliz?",
    #     "¿Cuál es tu mayor deseo?",
    #     "¿Cuál es tu lugar favorito en el mundo?",
    #     "¿Cuál es tu comida favorita?",
    #     "¿Cuál es tu mayor miedo?",
    #     "¿Cuál es tu bebida favorita?",
    #     "¿Qué te motiva a seguir adelante?",
    #     "¿Qué prefieres, el día o la noche?"
    # ]