# Generated by Django 4.2.13 on 2024-06-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreguntasApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
